version: '3'
services:
  server2:
    container_name: node-container-2
    build: 
      dockerfile: Dockerfile
    volumes:
      - .:/app
    ports:
      - 3336:3000

networks: 
  default: 
      name: cpl-world
      external: true